try {
  console.log("try");
  // throw 1234;
} catch (e) {
  console.log("error");
  console.log(e);
} finally {
  console.log("finally");
}
